"""Added new model - ConfigVersion

Revision ID: 1f4832ca2bcb
Revises: 22d5fe350415
Create Date: 2025-11-03 13:05:33.790893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f4832ca2bcb'
down_revision: Union[str, Sequence[str], None] = '22d5fe350415'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema: create config_versions table and indexes."""
    # ### commands auto generated by Alembic - adjusted ###
    op.create_table('config_versions',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('service_name', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('config_versions_pkey'))
    )
    op.create_index(op.f('ix_config_versions_service_name'), 'config_versions', ['service_name'], unique=False)
    op.create_index(op.f('ix_config_versions_id'), 'config_versions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema: drop indexes and config_versions table."""
    # ### commands auto generated by Alembic - adjusted ###
    op.drop_index(op.f('ix_config_versions_id'), table_name='config_versions')
    op.drop_index(op.f('ix_config_versions_service_name'), table_name='config_versions')
    op.drop_table('config_versions')
    # ### end Alembic commands ###
